name: t-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: [sync-Aaron-lv-sync,sync-smiek2221-scripts,sync-shufflewzc-faker2]
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Aaron-lv-sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Aaron-lv/sync.git"
          source_branch: "jd_scripts"
          destination_branch: "lv"
          github_token: ${{ secrets.PAT }}
          
  repo-sync1:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync smiek2221-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/smiek2221/scripts.git"
          source_branch: "master"
          destination_branch: "sm"
          github_token: ${{ secrets.PAT }}
          
  repo-sync2:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync shufflewzc-faker2
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/shufflewzc/faker2.git"
          source_branch: "main"
          destination_branch: "faker2"
          github_token: ${{ secrets.PAT }}
